---
title: "Homework 06"
author: "Spencer Pease"
date: "2/28/2020"
output: pdf_document
---

```{r setup, include=FALSE}

# Set output options
knitr::opts_chunk$set(echo = FALSE)
options(knitr.kable.NA = '-')

# Include libraries
library(dplyr)
library(readr)
library(ggplot2)
library(uwIntroStats)
library(aod)

# Helper functions
source("functions/summary_table.R")
source("functions/inference_table.R")

# Prepare data
wcgs <- read_csv("data/wcgs.csv") %>%
  transmute(
    age,
    chd = if_else(chd69 == "no", 0, 1),
    ab_personality = factor(dibpat)
  )

```

# _(Q1)_ Association between age and CHD events

```{r}
chd_age_lrm <- regress("odds", chd ~ age, data = wcgs)
chd_age_coef <- chd_age_lrm$fit$coefficients
```


## _(Q1.a)_

Fitted logistic regression model with _having a CHD event_ as the binary
response and _age_ and the predictor:

$$
E(chd \mid age) = \beta_0 + \beta_1 \cdot age
$$

```{r}
chd_age_inf <- chd_age_lrm %>%
  inference_table(include_intercept = TRUE) %>%
  mutate(`Pr(>|z|)` = format(`Pr(>|z|)`, digits = 3))

knitr::kable(
  chd_age_inf, booktabs = TRUE, digits = 2,
  caption = "Inferential statistics of log-odds CHD event vs age"
)

```

TBD

## _(Q1.b,c)_

```{r}
wcgs_aug <- wcgs %>%
  mutate(
    log_odds_chd = chd_age_coef[1] + age * chd_age_coef[2],
    prob_chd = exp(log_odds_chd) / (1 + exp(log_odds_chd))
  )

chd_age_plot_lo <- ggplot(wcgs_aug, aes(x = age, y = log_odds_chd)) +
  geom_point() +
  labs(
    title = "Log-Odds CHD event vs Age",
    x = "Age (years)",
    y = "Log-Odds CHD event"
  ) +
  theme_bw() +
  theme(text = element_text(family = "serif"))

chd_age_plot_pr <- ggplot(wcgs_aug, aes(x = age, y = prob_chd)) +
  geom_point() +
  labs(
    title = "Probability of CHD event vs Age",
    x = "Age (years)",
    y = "Probability of CHD event"
  ) +
  theme_bw() +
  theme(text = element_text(family = "serif"))
```

```{r fig.height=4}
chd_age_plot_lo
chd_age_plot_pr
```

## _(Q1.d)_

```{r}
chd_age_or_rr_tbl <- tibble(
  Age = seq(40, 60, 5),
  log_odds = chd_age_coef[1] + Age * chd_age_coef[2],
  Odds = exp(log_odds),
  `Prob.` = Odds / (1 + Odds),
  OR = Odds / lag(Odds),
  RR = `Prob.` / lag(`Prob.`)
)
```

```{r}
chd_age_or_rr_tbl %>%
  select(Age, `Prob.`, Odds, RR, OR) %>%
  knitr::kable(
    booktabs = TRUE, digits = 2,
    caption = "Calculated risk ratio (RR) and odds ratio (OR)"
  )
```

TBD

## _(Q1.e)_

```{r}
crit_val <- qnorm((1 - .95) / 2, lower.tail = FALSE)
chd_age_or5 <- (chd_age_inf[2, 2:3] * 5) %>%
  mutate(
    `95%L` = `Estimate` - crit_val * `Robust SE`,
    `95%H` = `Estimate` + crit_val * `Robust SE`
  ) %>%
  select(-`Robust SE`) %>%
  exp()
```


$$
OR_5 = \frac{Odds_{x+5}}{Odds_x}
= \frac{e^{\beta_0} e^{\beta_1 (x+5)}}{e^{\beta_0} e^{\beta_1 (x)}}
= e^{\beta_1 (x+5) - \beta_1 (x)}
= e^{\beta_1 (5)}
$$

```{r}
knitr::kable(
  chd_age_or5, booktabs = TRUE, digits = 2,
  caption = "Odds ratio comparing men 5 years apart in age"
)
```

TBD

## _(Q1.f)_


## _(Q1.g)_

```{r}
lrt_test <- aod::anova(glm(chd~1, data = wcgs), glm(chd~age, data = wcgs), test = "LRT")
```


# _(Q2)_ Association between personality and CHD events

## _(Q2.a)_
## _(Q2.b)_
## _(Q2.c)_
## _(Q2.d)_
## _(Q2.e)_
